name: Update README posts

on:
  workflow_dispatch:
  schedule:
    # Runs every 5 hours
    - cron: "*/5 * * * *"
jobs:
  update-posts:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
    - uses: actions/checkout@v2
    - name: Instalar dependencias Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Actualizars posts
      run: |
        python main.py
      env:
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}